### PR TITLE
Full update

### PR DESCRIPTION
**Pull request by yalh76**
## Problem
- *Old Package*

## Solution
- [x] *Apply example_ynh*
- [x] *Switch from repository to app.src*
- [x] *Implement backup and restore*
- [x] *Apply last example_ynh*

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
- [ ] **Code review**
- [ ] **Approval (LGTM)**  
*Code review and approval have to be from a member of @YunoHost/apps group*
- **CI succeeded** : 
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/syncthing_ynh_PR12%20(yalh76)/)  

Revision: f7b54170297fcf5d6bc5fc97f7be5f5c48df1a75
f7b54170297fcf5d6bc5fc97f7be5f5c48df1a75

When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by yalh76** [comment]
PR is ready to be tested

**Comment by yalh76** [comment]
@tuxmouraille have you got time to review this PR or give me rights to merge it ?

**Comment by tuxmouraille** [comment]
@yalh76 Thanks you for your work. I can't give you rights to merge, because I am not any-more owner of this repository. Can you ask for to YunoHost-Apps admin, please?

**Comment by yalh76** [comment]
thanks @tuxmouraille 

@kay0u can you give me rigths on the syncthing_ynh repository, @tuxmouraille agrees :)

**Comment by kay0u** [comment]
Done! :-)

**Pull request merged**
