### PR TITLE
Enable multi_instance

### PR DESCRIPTION
**Pull request by tituspijean**
[This thread](https://forum.yunohost.org/t/syncthing-multi-utilisateur/16372) on the forum got me trying installing multiple instances of Syncthing, and it seems to be working!

I concede that being forced to have one app per user is not ideal, but we are constrained with Syncthing's own design. I am sure there are plenty of use cases for this.

Tested without issues:
- [x] Two instances sharing files locally
- [x] Two instances locally, one of which sharing files externally

### CODE REVIEW

**Comment by tituspijean** [comment]
!testme

**Comment by yalh76** [comment]
I think it won't work:
- https://docs.syncthing.net/users/firewall.html
- https://forum.syncthing.net/t/two-syncthing-instances-in-one-machine/16162/7

Syncthing requires `a port forwarding for ports 22000/TCP and 22000/UDP`

**Comment by tituspijean** [comment]
After further investigation, indeed one of the two instances fails to connect directly *but* thanks to Syncthing's integrated relay server feature, connection can still be made. 😉

**Comment by tituspijean** [comment]
Upon even further investigation, I retract my last comment. Specifying the actual `listenAddress`es in the configuration file instead of `default` (which indeed defaults to port 22000), it works flawlessly and without relay.

**Comment by yalh76** [comment]
!testme

**Pull request merged**
